# Travis.ci file https://docs.travis-ci.com/user/tutorial/
# Continuous integration

# Login to https://travis-ci.com/ using your github credentials
# Add this repository to travis
# Every time there is a commit, this script will be run and result emailed

language: cpp

dist: xenial

# Removed, not using valgrind 
#   - sudo apt-get install valgrind
before_install:
  - uname -a
  - clang++ --version
  - clang-tidy --version
  - valgrind --version



script:
    - ./simplecompile.sh
    - echo "Travis is done!"
