# Travis.ci file https://docs.travis-ci.com/user/tutorial/
# Continuous integration

# Login to https://travis-ci.com/ using your github credentials
# Add this repository to travis
# Every time there is a commit, this script will be run and result emailed

language: cpp

dist: xenial

# Removed, not using valgrind 
#   - sudo apt-get install valgrind
#   - valgrind --version
# Removed to simplecompile script
#   - clang++ --version
#   - clang-tidy --version
before_install:
  - uname -a

script:
    - ./simplecompile.sh
    - echo "Travis is done!"
